name: API Automation Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:  

jobs:
  selenium-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '23'
        distribution: 'temurin'

    - name: Setup Gradlew
      run: chmod +x gradlew
    
    - name: Execute Tests
      run: ./gradlew test

    - name: Generate Allure Report
      run: ./gradlew allureReport

    - name: Archive Test Results
      uses: actions/upload-artifact@v4.4.3
      with:
        name: reports
        path: reports

    - name: Upload Allure Report to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build/reports/allure-report
      if: always()
