name: API Automation Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:  

jobs:
  selenium-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Gradlew
      run: chmod +x gradlew
    
    - name: Execute Tests
      run: ./gradlew test

    - name: Archive Test Results
      uses: actions/upload-artifact@v4.4.3
      with:
        name: Test Reports
        path: ./build/reports

    - name: Build test report
      uses: simple-elf/allure-report-action@v1.9
      if: always()
      with:
          gh_pages: gh-pages
          allure_history: allure-history
          allure_results: build/allure-results

    - name: Publish test report
      uses: peaceiris/actions-gh-pages@v3
      if: always()
      with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history
